/**
 * shadcn/ui toast store: a module-level reducer plus a listener list, so `toast()` can be
 * called from anywhere (components or plain modules) without a React provider.
 * `useToast()` subscribes a component to that store; src/components/ui/toaster.tsx renders
 * the resulting `toasts`. Login, Register, AcceptInvite and ResetPassword use `useToast`;
 * src/components/ui/use-toast.ts re-exports both exports.
 */
import * as React from "react";

import type { ToastActionElement, ToastProps } from "@/components/ui/toast";

/** Maximum number of toasts kept in state at once; a new toast evicts the older one. */
const TOAST_LIMIT = 1;
/**
 * Milliseconds a dismissed toast (`open: false`) stays in state before REMOVE_TOAST
 * deletes it (about 16 minutes).
 */
const TOAST_REMOVE_DELAY = 1000000;

/** A toast as stored in state: Radix toast props plus an id and renderable content. */
type ToasterToast = ToastProps & {
  id: string;
  title?: React.ReactNode;
  description?: React.ReactNode;
  action?: ToastActionElement;
};

const actionTypes = {
  ADD_TOAST: "ADD_TOAST",
  UPDATE_TOAST: "UPDATE_TOAST",
  DISMISS_TOAST: "DISMISS_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",
} as const;

let count = 0;

/** Returns the next toast id: an incrementing counter as a string, wrapping before MAX_SAFE_INTEGER. */
function genId() {
  count = (count + 1) % Number.MAX_SAFE_INTEGER;
  return count.toString();
}

type ActionType = typeof actionTypes;

type Action =
  | {
      type: ActionType["ADD_TOAST"];
      toast: ToasterToast;
    }
  | {
      type: ActionType["UPDATE_TOAST"];
      toast: Partial<ToasterToast>;
    }
  | {
      type: ActionType["DISMISS_TOAST"];
      toastId?: ToasterToast["id"];
    }
  | {
      type: ActionType["REMOVE_TOAST"];
      toastId?: ToasterToast["id"];
    };

interface State {
  toasts: ToasterToast[];
}

/** Pending removal timers keyed by toast id, so each toast is scheduled for removal at most once. */
const toastTimeouts = new Map<string, ReturnType<typeof setTimeout>>();

/** Schedules REMOVE_TOAST for `toastId` after TOAST_REMOVE_DELAY; ignored if already scheduled. */
const addToRemoveQueue = (toastId: string) => {
  if (toastTimeouts.has(toastId)) {
    return;
  }

  const timeout = setTimeout(() => {
    toastTimeouts.delete(toastId);
    dispatch({
      type: "REMOVE_TOAST",
      toastId: toastId,
    });
  }, TOAST_REMOVE_DELAY);

  toastTimeouts.set(toastId, timeout);
};

/**
 * Toast state transitions. ADD puts the newest toast first and trims to TOAST_LIMIT; UPDATE
 * merges into the toast with the same id; DISMISS marks one toast (or all, when no id is
 * given) `open: false` and schedules its removal; REMOVE deletes one toast (or all).
 */
export const reducer = (state: State, action: Action): State => {
  switch (action.type) {
    case "ADD_TOAST":
      return {
        ...state,
        toasts: [action.toast, ...state.toasts].slice(0, TOAST_LIMIT),
      };

    case "UPDATE_TOAST":
      return {
        ...state,
        toasts: state.toasts.map((t) => (t.id === action.toast.id ? { ...t, ...action.toast } : t)),
      };

    case "DISMISS_TOAST": {
      const { toastId } = action;

      // ! Side effects ! - This could be extracted into a dismissToast() action,
      // but I'll keep it here for simplicity
      if (toastId) {
        addToRemoveQueue(toastId);
      } else {
        state.toasts.forEach((toast) => {
          addToRemoveQueue(toast.id);
        });
      }

      return {
        ...state,
        toasts: state.toasts.map((t) =>
          t.id === toastId || toastId === undefined
            ? {
                ...t,
                open: false,
              }
            : t,
        ),
      };
    }
    case "REMOVE_TOAST":
      if (action.toastId === undefined) {
        return {
          ...state,
          toasts: [],
        };
      }
      return {
        ...state,
        toasts: state.toasts.filter((t) => t.id !== action.toastId),
      };
  }
};

/** State setters of every mounted `useToast` consumer; notified after each dispatch. */
const listeners: Array<(state: State) => void> = [];

/** The single shared toast state, kept outside React so `toast()` works from any module. */
let memoryState: State = { toasts: [] };

/** Applies `action` to the shared state and pushes the new state to all listeners. */
function dispatch(action: Action) {
  memoryState = reducer(memoryState, action);
  listeners.forEach((listener) => {
    listener(memoryState);
  });
}

/** Caller-supplied toast options; the id is always generated by `toast()`. */
type Toast = Omit<ToasterToast, "id">;

/**
 * Shows a toast and returns its `id` plus `dismiss()` and `update(props)` handles for it.
 * Callable outside React components; it only dispatches to the module-level store.
 */
function toast({ ...props }: Toast) {
  const id = genId();

  const update = (props: ToasterToast) =>
    dispatch({
      type: "UPDATE_TOAST",
      toast: { ...props, id },
    });
  const dismiss = () => dispatch({ type: "DISMISS_TOAST", toastId: id });

  dispatch({
    type: "ADD_TOAST",
    toast: {
      ...props,
      id,
      open: true,
      // Radix calls this when the toast closes itself (timeout, swipe, close button).
      onOpenChange: (open) => {
        if (!open) dismiss();
      },
    },
  });

  return {
    id: id,
    dismiss,
    update,
  };
}

/**
 * Subscribes the calling component to the shared toast store. Returns the current
 * `toasts` plus the `toast` function and a `dismiss(toastId?)` helper (no id dismisses all).
 */
function useToast() {
  const [state, setState] = React.useState<State>(memoryState);

  // The effect depends on `state`, so the listener is removed and re-added after every
  // state change; the cleanup keeps the listener list free of duplicates.
  React.useEffect(() => {
    listeners.push(setState);
    return () => {
      const index = listeners.indexOf(setState);
      if (index > -1) {
        listeners.splice(index, 1);
      }
    };
  }, [state]);

  return {
    ...state,
    toast,
    dismiss: (toastId?: string) => dispatch({ type: "DISMISS_TOAST", toastId }),
  };
}

export { useToast, toast };
